const problems = [
  {
    title: "Two Sum",
    topic: "Arrays",
    difficulty: "Easy",
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["Array", "HashMap"],
    url: "https://leetcode.com/problems/two-sum/",
    frequency: 5,
  },
  {
    title: "Best Time to Buy and Sell Stock",
    topic: "Arrays",
    difficulty: "Easy",
    companies: ["Amazon", "Microsoft"],
    tags: ["Array"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    frequency: 5,
  },
  {
    title: "Contains Duplicate",
    topic: "Arrays",
    difficulty: "Easy",
    companies: ["Amazon", "Google"],
    tags: ["Array", "HashSet"],
    url: "https://leetcode.com/problems/contains-duplicate/",
    frequency: 4,
  },
  {
    title: "Valid Anagram",
    topic: "Strings",
    difficulty: "Easy",
    companies: ["Amazon", "Adobe"],
    tags: ["String", "HashMap"],
    url: "https://leetcode.com/problems/valid-anagram/",
    frequency: 4,
  },
  {
    title: "Valid Parentheses",
    topic: "Stack",
    difficulty: "Easy",
    companies: ["Amazon", "Google"],
    tags: ["Stack"],
    url: "https://leetcode.com/problems/valid-parentheses/",
    frequency: 5,
  },
  {
    title: "Binary Search",
    topic: "Binary Search",
    difficulty: "Easy",
    companies: ["Microsoft", "Google"],
    tags: ["Binary Search"],
    url: "https://leetcode.com/problems/binary-search/",
    frequency: 4,
  },
  {
    title: "Merge Two Sorted Lists",
    topic: "Linked List",
    difficulty: "Easy",
    companies: ["Amazon", "Microsoft"],
    tags: ["Linked List"],
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    frequency: 5,
  },
  {
    title: "Maximum Subarray",
    topic: "Arrays",
    difficulty: "Medium",
    companies: ["Amazon", "Google"],
    tags: ["Kadane"],
    url: "https://leetcode.com/problems/maximum-subarray/",
    frequency: 5,
  },
  {
    title: "3Sum",
    topic: "Arrays",
    difficulty: "Medium",
    companies: ["Amazon", "Adobe"],
    tags: ["Two Pointer"],
    url: "https://leetcode.com/problems/3sum/",
    frequency: 5,
  },
  {
    title: "Product of Array Except Self",
    topic: "Arrays",
    difficulty: "Medium",
    companies: ["Amazon", "Microsoft"],
    tags: ["Prefix Sum"],
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    frequency: 5,
  },
];

module.exports = problems;